### ISSUE TITLE
Recommended lights

### ISSUE THREAD

**Issue by monkbroc** [lumiere-lighting/lumiere-server#1]
Very cool project! I saw it through the Code for America mailing list.

Do you have recommendations of LED light strips that could be used with Lumière? I know of the NeoPixel by Adafruit, but any other you are aware of, especially ones that could be used outside?

**Comment by zzolo** [comment]
Hey @monkbroc.

I have been making repos for different micro controllers in this organization:
https://github.com/lumiere-lighting

But, the most stable/reliable is probably an Arduino Yun with NeoPixels
https://github.com/lumiere-lighting/lumiere-node-arduino-yun

NeoPixels come with weather stripping on them.  I have some outside right now.

I have also used the LPD8806 led strips from Adafruit successfully.  The Arduino code uses FastLED which supports a number of different strips.  If you use a different microcontroller, then NeoPixels are gonna probably be the only supported way to go.  though, if you use a Raspberry Pi, the LPD8806 are a good choice.

I plan on making a code page/site with more stuff like this.

**Comment by zzolo** [comment]
A little bit more on outside/weatherproof stuff.  I have the actual controller inside the house.  Though I put it in a waterproof box and its not far off from being safe outside, it's actually easy for me to have inside.

I did solder on waterproof connectors to the lights and used some glue and shrinkwrap to seal some edges on things.
https://www.adafruit.com/product/744

**Comment by dmccreary** [comment]
I usually search for "WS2812b" on ebay.  These are the packaging standards
for the items on the tape.

Here is a popular one:

http://www.ebay.com/itm/WS2812B-WS2811-RGB-LED-Strip-5M-150-300-Leds-60LED-M-Individual-Addressable-5V-/231105154168

You can get a 1 meter strip with 60 LEDs for about $20.  It takes about two
weeks to arrive from China.

I also use the NeoPixel library.  I have not yet found a low-cost supplier
of the Yun yet.
- Dan

On Fri, Dec 12, 2014 at 11:40 AM, Julien Vanier notifications@github.com
wrote:

> Very cool project! I saw it through the Code for America mailing list.
> 
> Do you have recommendations of LED light strips that could be used with
> Lumière? I know of the NeoPixel by Adafruit, but any other you are aware
> of, especially ones that could be used outside?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lumiere-lighting/lumiere-server/issues/1.

## 

Dan McCreary
Principal Consultant, MarkLogic
Co-author: Making Sense of NoSQL http://manning.com/mccreary
office: (952) 931-9198
cell: (612) 986-1552
skype: dmccreary47

**Comment by monkbroc** [comment]
Thanks. I have a Spark already so I'll try with that micro.

**Comment by zzolo** [comment]
I am not sure if its the code or the Spark or both, and I have not found a great way to debug, but with the current Spark code that's up there, the Spark will intermittently disconnect from the network and hard fault.  Often this is just at "startup" and it works okay after that.  But overall, my feeling is that the Spark is not stable (with that code).
